name = "Ballscratcher"
author = "Cwavs, Jacket, Liam, Ned"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4b5a0b84a7dd5032f8772e9d12b975a11a60824fd023d9fa91801f63fd5837cf"

[versions]
forge = "47.1.44"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20", "1.20.1"]
