name = "Ballscratcher"
author = "Cwavs, Jacket, Liam, Ned"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "949f6243f40b5175e001d07414831cc0e7964b71fbe636de4f7528d01c8b7482"

[versions]
forge = "47.1.44"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20", "1.20.1"]
