name = "Ballscratcher"
author = "Cwavs, Jacket, Liam, Ned"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8124543530cf93361edf731964f9a426a884087ec12ddd345282ad90d3f3daa3"

[versions]
forge = "47.1.44"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20", "1.20.1"]
