name = "Ballscratcher"
author = "Cwavs, Jacket, Liam, Ned"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0151d9a6cc791902d621a71435886e949210b3d8c2faa85b3ccf2115b0a45123"

[versions]
forge = "47.1.44"
minecraft = "1.20.1"
