name = "Ballscratcher"
author = "Cwavs, Jacket, Liam, Ned"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "31a1231b50736cec675f87d22fc523a525233256c630600670ee7f3b6526b062"

[versions]
forge = "47.1.44"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20", "1.20.1"]
