name = "Ballscratcher"
author = "Cwavs, Jacket, Liam, Ned"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b7269c0aa4411a9e82ca8e696e6a3e78d256abaecf024881723b7fff38aa007b"

[versions]
forge = "47.1.44"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20", "1.20.1"]
